name: "Continuous Integration"

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main", "wip/**"]

jobs:
  ci:
    name: "Basic Test"
    container:
      image: "ghcr.io/bus1/ci-c-util:latest"
    runs-on: "ubuntu-latest"

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v3
    - name: "Prepare Build"
      working-directory: "./test/basic/"
      run: meson setup build
    - name: "Run Build"
      working-directory: "./test/basic/"
      run: meson compile -v -C build
    - name: "Run Meson Tests"
      working-directory: "./test/basic/"
      run: meson test -v -C build
    - name: "Run Dist"
      working-directory: "./test/basic/"
      run: meson dist -v -C build --include-subprojects
    - name: "Build Cargo Targets"
      working-directory: "./test/basic/"
      run: cargo build --verbose --all-targets
    - name: "Run Cargo Tests"
      working-directory: "./test/basic/"
      run: cargo test --verbose
